#!/bin/bash
# 🚀 AWS Free Tier Account Setup

echo "🐝 AWS FREE TIER SETUP"
echo "======================"
echo ""

# Open AWS signup page
open -a "Google Chrome" "https://portal.aws.amazon.com/billing/signup"

echo "📋 AWS SIGNUP STEPS:"
echo ""
echo "1. Click 'Create a new AWS account'"
echo ""
echo "2. Fill in your details:"
echo "   - Email: your email"
echo "   - Password: create strong password"
echo "   - AWS account name: kmsitecontruction"
echo ""
echo "3. Personal/Business account:"
echo "   - Select: Personal"
echo "   - Full name: Your name"
echo "   - Phone: Your phone"
echo "   - Country: Select yours"
echo ""
echo "4. Payment Information:"
echo "   - Credit/debit card required (for verification)"
echo "   - Won't be charged on free tier"
echo ""
echo "5. Identity Verification:"
echo "   - Enter code sent to phone"
echo ""
echo "6. Support Plan:"
echo "   - Select: Basic Support (Free)"
echo ""
echo "7. ✅ Complete signup!"
echo ""
echo "📍 After signup, go to EC2 to launch instance:"
echo "   https://console.aws.amazon.com/ec2"
echo ""
echo "🎉 Once EC2 is running, run:"
echo "   ./deploy-to-aws.sh"
